const URLList = {
  AdminCustomerURL: "admin/customer",
  AdminCustomerCarURL: "admin/customer-car",
  AdminCarSizeURL: "admin/carsize",
  ProvinceURL: "admin/province",
  AdminService: "admin/service",
  AdminChannel: "admin/channel",
  AdminOnLeaveType: "admin/onleave/type",
  AdminPaymentType: "admin/paymenttype",
  AdminStaff: "admin/user",
  AdminStatusGroup: "admin/status-group",
  AdminStatus: "admin/status",
  AdminRole: "admin/role",
  AdminRoleLabel: "admin/role-label",
  AdminOnLeavePersonal: "admin/onleave/personal",
  AdminOnLeave: "admin/onleave",
  AdminOnLeaveApprove: "admin/onleave/approve",
  AdminLatestOnLeaveByTypePersonal: "admin/onleave/detail/latest/personal",
  AdminLatestOnLeaveByTypeList: "admin/onleave/detail/latest/list",
  AdminPermission: "admin/permission",
  AdminTemplate: "admin/template",
  AdminSearch: "admin/search",
};

export default URLList;
