const URLList = {
  //Admin
  AdminCustomer: "admin/customer",
  AdminCustomerCar: "admin/customer-car",
  AdminCarSize: "admin/carsize",
  AdminService: "admin/service",
  AdminChannel: "admin/channel",
  AdminOnLeaveType: "admin/onleave/type",
  AdminPaymentType: "admin/paymenttype",
  AdminStaff: "admin/user",
  AdminStatus: "admin/status",
  AdminRole: "admin/role",
  AdminRoleLabel: "admin/role-label",
  AdminOnLeavePersonal: "admin/onleave/personal",
  AdminOnLeave: "admin/onleave",
  AdminOnLeaveApprove: "admin/onleave/approve",
  AdminLatestOnLeaveByTypePersonal: "admin/onleave/detail/latest/personal",
  AdminLatestOnLeaveByTypeList: "admin/onleave/detail/latest/list",
  AdminPermission: "admin/permission",
  AdminTemplate: "admin/template",
  AdminSearch: "admin/search",
  AdminLogin: "admin/login",
  AdminGeneral: "admin/general",
  Modules: "admin/module",
  RolePermission: "admin/role-permission",
  Province: "admin/province",
  AdminStatusGroup: "admin/status-group",
  PaymentAccount: "admin/payment-account",
  Branch: "admin/branch",
};

export default URLList;
