TRUNCATE TABLE `menu_items`;

INSERT INTO `menu_items` (`name`, `icon`, `parent_alias`, `alias`) VALUES
('Home', 'ri-home-line', NULL, 'home'),
('Schedule page | ตารางงาน', 'ri-calendar-line', NULL, 'schedule'),
('Booking', 'ri-user-line', NULL, 'booking'),
('Payment History | ประวัติการชําระเงิน', NULL, NULL, 'payment'),
('User', 'ri-calendar-line', NULL, 'user'),
('Staff', NULL, 'user', 'staff'),
('Customer', NULL, 'user', 'customer'),
('Customer car', NULL, 'user', 'customerCar'),
('Onleave Personal', NULL, NULL, 'onLeavePersonal'),
('DayOff List', NULL, NULL, 'dayOffList'),
('Setting', NULL, NULL, 'setting'),
('Car size', 'ri-user-line', 'setting', 'carSize'),
('Service', 'ri-settings-2-line', 'setting', 'service'),
('Channel', 'ri-user-line', 'setting', 'channel'),
('Template', NULL, 'setting', 'template'),
('Search', NULL, 'setting', 'search'),
('Role', 'ri-logout-box-line', 'setting', 'role'),
('Account', NULL, 'setting', 'account'),
('Onleave List', 'ri-logout-box-line', 'setting', 'onLeaveList'),
('Status', 'ri-user-line', 'setting', 'status'),
('Onleave Type', NULL, 'setting', 'onLeaveType'),
('Payment Type', NULL, 'setting', 'paymentType'),
('Advance Setting', NULL, 'setting', 'advSetting');
