SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS `branch`;

CREATE TABLE IF NOT EXISTS `branch` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `name` VARCHAR(100) NOT NULL,
  `address` VARCHAR(255),
  `phone` VARCHAR(20)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

SET FOREIGN_KEY_CHECKS = 1;
