DROP TABLE IF EXISTS `car_size`;

CREATE TABLE IF NOT EXISTS `car_size`  (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `size` VARCHAR(30) UNIQUE NOT NULL,
  `is_available` TINYINT DEFAULT 1
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
