SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS `car_size`;

CREATE TABLE IF NOT EXISTS `car_size`  (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `size` VARCHAR(30) UNIQUE NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

SET FOREIGN_KEY_CHECKS = 1;
