DROP TABLE IF EXISTS `channel`;

CREATE TABLE IF NOT EXISTS `channel`  (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `name` VARCHAR(30) UNIQUE NOT NULL,
  `max_capacity` INT NOT NULL,
  `is_available` TINYINT DEFAULT 1
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;