SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS `module`;

CREATE TABLE IF NOT EXISTS `module` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `code` VARCHAR(50) NOT NULL,      
  `name` VARCHAR(100) NOT NULL, 
  `parent_id` INT DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

SET FOREIGN_KEY_CHECKS = 1;