DROP TABLE IF EXISTS `payment_type`;

CREATE TABLE IF NOT EXISTS `payment_type` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `code` VARCHAR(20) UNIQUE NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  `is_online` TINYINT(1) DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
