DROP TABLE IF EXISTS `permission`;

CREATE TABLE IF NOT EXISTS `permission` (
  `id` INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `role_id` INT(11) NOT NULL,
  `page_alias` VARCHAR(50) NOT NULL,
  `access` TINYINT(1) NOT NULL DEFAULT 0,
  `add` TINYINT(1) NOT NULL DEFAULT 0,
  `edit` TINYINT(1) NOT NULL DEFAULT 0,
  `delete` TINYINT(1) NOT NULL DEFAULT 0,
  `approve` TINYINT(1) NOT NULL DEFAULT 0,
  FOREIGN KEY (`role_id`) REFERENCES `role`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


-- add role_id and make it FK
