SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS `province`;

CREATE TABLE IF NOT EXISTS `province`  (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `province` VARCHAR(50) UNIQUE NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

SET FOREIGN_KEY_CHECKS = 1;