SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS `service`;

CREATE TABLE IF NOT EXISTS `service`  (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `name` VARCHAR(30) UNIQUE NOT NULL,
  `is_available` TINYINT DEFAULT 1
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

SET FOREIGN_KEY_CHECKS = 1;