DROP TABLE IF EXISTS `status_group`;

CREATE TABLE IF NOT EXISTS `status_group`  (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `code` VARCHAR(30) UNIQUE NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
